name: test and coverage

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        dart_channel: ['stable']

      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: packages/string_literal_finder
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart_channel }}
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart run test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: dev
      - run: cd packages/string_literal_finder && _tool/test-coverage.sh
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        env:
          COVERALLS_FLAG_NAME: Unit
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/string_literal_finder
          path-to-lcov: packages/string_literal_finder/coverage/lcov.info
#          base-path: .

